.TH 3ds2rib 1 "16 Jun 2001" Version 1.1.0
.SH NAME
3ds2rib - Simple 3DS to RIB (RenderMan Interface Bytestream) converter.
.SH SYNOPSIS
.B 3ds2rib
[options] filename [options]
.SH DESCRIPTION
.PP
\fI3ds2rib\fP is a tool to convert 3DS files into RIB 
(RenderMan Interface Bytestream) files.
.SH OPTIONS
.l
\fI3ds2rib\fP accepts the following options:
.TP 8
.B -h/--help
This help
.TP 8
.B -o/--output <filename>
Write output to <filename> instead of stdout
.TP 8
.B -c/--camera <name>
Use camera <name> for rendering
.TP 8
.B -a/--all
Render all frames
.TP 8
.B -f/--frame #
Render frame #
.TP 8
.B -d/--downcuts #
Render # frames of animation
.SH COPYRIGHT
3ds2rib Copyright \(co 1996-2001 by J.E. Hoffmann <je-h@gmx.net>
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.








